[package]
name = "tari_dan_app_utilities"
version = "0.50.0-pre.0"
authors = ["The Tari Development Community"]
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", tag = "v0.50.0-pre.1" }
tari_core = { git = "https://github.com/tari-project/tari.git", tag = "v0.50.0-pre.1", default-features = false, features = ["transactions"] }
tari_crypto = { version = "0.16" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", tag = "v0.50.0-pre.1" }

tari_dan_common_types = { path = "../../dan_layer/common_types" }
tari_dan_core = { path = "../../dan_layer/core" }
tari_dan_engine = { path = "../../dan_layer/engine" }
tari_dan_storage = { path = "../../dan_layer/storage" }
tari_dan_storage_sqlite = { path = "../../dan_layer/storage_sqlite" }
tari_engine_types = { path = "../../dan_layer/engine_types" }
tari_epoch_manager = { path = "../../dan_layer/epoch_manager", features = ["base_layer"] }
tari_base_node_client = { path = "../../clients/base_node_client" }
tari_template_builtin = { path = "../../dan_layer/template_builtin" }
tari_template_lib = { path = "../../dan_layer/template_lib" }
tari_transaction = { path = "../../dan_layer/transaction" }
tari_validator_node_client = { path = "../../clients/validator_node_client" }

anyhow = "1.0.53"
bytes = "1"
chrono = "0.4.22"
futures = { version = "^0.3.1" }
lazy_static = "1.4.0"
log = { version = "0.4.8", features = ["std"] }
mini-moka = "0.10.0"
prost = "0.9"
reqwest = "0.11.11"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "^1.0.20"
tokio = { version = "1.10", features = ["macros", "time", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1.7", features = ["sync"] }
