[package]
name = "tari_consensus"
version = "0.50.0-pre.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
tari_dan_common_types = { path = "../common_types" }
tari_dan_storage = { path = "../storage" }
tari_transaction = { path = "../transaction" }
tari_epoch_manager = { path = "../epoch_manager" }

# Used for PublicKey and Signature
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_mmr = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", branch = "development" }

anyhow = "1.0"
async-trait = "0.1.68"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1", default-features = false, features = ["sync"] }
