[package]
name = "tari_consensus"
version = "0.50.0-pre.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
tari_dan_common_types = { path = "../common_types" }
tari_dan_storage = { path = "../storage" }

# Used for PublicKey and Signature
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_mmr = { git = "https://github.com/tari-project/tari.git", tag = "v0.50.0-pre.1" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", branch = "development" }

async-trait = "0.1.68"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["sync"] }
