[package]
name = "tari_dan_storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common = { workspace = true }
tari_common_types = { workspace = true }
tari_dan_common_types = { workspace = true }

# Shard store deps
tari_engine_types = { workspace = true }
tari_transaction = { workspace = true }
tari_core = { workspace = true, default-features = true }
tari_crypto = { workspace = true }
tari_state_tree = { workspace = true }
tari_bor = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
log = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, default-features = true }
time = { workspace = true, features = ["serde"] }
ts-rs = { workspace = true, optional = true }

[features]
ts = ["ts-rs"]
