[package]
name = "tari_dan_storage"
version = "0.50.0-pre.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", ref = "c490298783237c6efb5942fe733aa8c939415018" }
tari_dan_common_types = { path = "../common_types" }
tari_utilities = "0.4.10"

# Shard store deps
tari_engine_types = { path = "../engine_types" }
tari_transaction = { path = "../transaction" }
tari_core = { git = "https://github.com/tari-project/tari.git", ref = "c490298783237c6efb5942fe733aa8c939415018" }
tari_mmr = { git = "https://github.com/tari-project/tari.git", ref = "c490298783237c6efb5942fe733aa8c939415018" }

chrono = "0.4.23"
log = "0.4"
thiserror = "1"
serde = "1.0"
