[package]
name = "tari_dan_storage"
version = "0.50.0-pre.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", tag = "v0.49.0-pre.0", package = "tari_common_types" }
tari_dan_common_types = { path = "../common_types" }

thiserror = "1"
time = "0.3.15"
serde = "1.0"