[package]
name = "tari_dan_storage"
version = "0.0.6"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_dan_common_types = { path = "../common_types" }

# Shard store deps
tari_engine_types = { path = "../engine_types" }
tari_transaction = { path = "../transaction" }
tari_core = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_mmr = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_crypto = "0.19"
tari_utilities = "0.6"
tari_bor = { path = "../tari_bor" }

anyhow = "1.0"
chrono = "0.4.23"
log = "0.4"
rand = "0.8"
thiserror = "1"
serde = "1.0"
time = { version = "0.3", features = ["serde"] }
