[package]
name = "tari_validator_node_client"
version = "0.50.0-pre.0"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Tari validator node client library"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_dan_common_types = { path = "../../dan_layer/common_types" }
tari_engine_types = { path = "../../dan_layer/engine_types" }
tari_common_types = { git = "https://github.com/tari-project/tari.git", rev = "c490298783237c6efb5942fe733aa8c939415018" }
tari_comms_logging = { path = "../../comms/tari_comms_logging" }
tari_transaction = { path = "../../dan_layer/transaction" }
tari_dan_storage = { path = "../../dan_layer/storage" }

reqwest = { version = "0.11.11", features = ["json"] }
multiaddr = "0.14"
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0"
