[package]
name = "tari_template_test_tooling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tari_dan_engine = { path = "../engine" }
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", tag = "v0.16.6" }
tari_template_lib = { path = "../template_lib", default-features = false, features = ["serde"] }
tari_engine_types = { path = "../engine_types" }
tari_transaction_manifest = { path = "../transaction_manifest" }
tari_template_builtin = { path = "../template_builtin" }
tari_transaction = { path = "../transaction" }
tari_dan_common_types = { path = "../common_types", features=["rand"] }

anyhow = "1.0.68"
borsh = "0.9.3"
